server:
  port: 9997
spring:
  application:
    name: jyt
  profiles:
    active: dev
  datasource:
    datasourcemz:
      username: mzhis
      password: mzhis
      jdbc-url: jdbc:oracle:thin:@100
      driver-class-name: oracle.jdbc.driver.OracleDriver
    datasourcezy:
      username: tthis
      password: tthis
      jdbc-url: jdbc:oracle:thin:@zytest
      driver-class-name: oracle.jdbc.driver.OracleDriver
mybatis:
  mapper-locations: classpath:com/ljh/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:logback-spring.xml

#mybatis-plus:
#  config-location: classpath:mybatis-plus-config.xml
