server:
  port: 8080
spring:
  datasource:
    username: mzhis
    password: mzhis
    url: jdbc:oracle:thin:@100
    driver-class-name: oracle.jdbc.driver.OracleDriver
mybatis:
  mapper-locations: classpath:com/ljh/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      ljh:
        mapper:
          common: debug
